### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by MrHen** [moznion/gulp-tsd#8]
gulp-tsd is frequently failing in our travis runs with this output:

```
[15:53:11] [gulp-tsd] execute command: reinstall
[15:53:11] [gulp-tsd] config: typings/tsd.json
[15:53:12] [gulp-tsd] latest: false
[15:53:12] [gulp-tsd] running...
/home/travis/build/smartsocialmedia/ssm-server/node_modules/gulp-tsd/index.js:24
        promise.done(function () {
                ^
TypeError: Cannot call method 'emit' of undefined
```

I assume some sort of error from tsd is being generated but I can't tell what it is because of the `undefined` issue. Anyone know what is causing this?

**Comment by moznion** [comment]
I cannot identify the cause because it lacks of information.
Could you give me more details?

**Comment by MrHen** [comment]
The lack of details is because of the `undefined` error. I don't really have more information. I suspect something in `gulp-tsd` is masking an actual error from tsd but I don't have any real way to debug this via travis. It never repros locally.

**Comment by moznion** [comment]
Does it occur on forked gulp-tsd repository's CI? Or any project which is used gulp-tsd is failed?

**Comment by moznion** [comment]
I want information of your project, content of your .travis.yml, and testing command if it is possible.

**Comment by MrHen** [comment]
Our code is in a private GitHub repo that uses Travis and we install gulp-tsd via npm. Our package.json has `"gulp-tsd": "0.0.3"`. I'll try updating to the latest version to see if it fixes the issue.

**Comment by moznion** [comment]
Please :bow:

**Comment by MrHen** [comment]
`.travis.yml`:

```
sudo: false
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
env:
  global:
    - AMAZON_NAMESPACE=travis
    - secure: "**removed**"
    - secure: "**removed**"
  matrix:
    - NODE_ENV=test ELASTICSEARCH_HOST=localhost ELASTICSEARCH_PORT=9200 MONGO_URL=mongodb://127.0.0.1/ssm-test
addons:
  apt:
      packages:
          - graphicsmagick
before_install:
  - npm install -g npm@latest
  - npm install -g gulp
install:
  - npm install
notifications:
  template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
  slack:
    rooms:
      - secure: "**removed**"
services:
  - mongodb
  - elasticsearch
branches:
  only:
    - /^develop.*$/
    - /^release.*$/
    - /^t-.*$/
```
